#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
# wall &
feh --bg-fill ~/.wall/6.jpg &

bspc monitor -d 1 2 3 4 5

bspc config border_width  0
bspc config window_gap   10

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
